# Generated by Django 4.2.14 on 2024-07-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0003_landingbanner_delete_landing_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='landing_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default='Default description', max_length=255)),
                ('image', models.ImageField(upload_to='statc/forntpage/img/landing_banner')),
            ],
        ),
        migrations.DeleteModel(
            name='landingBanner',
        ),
    ]
