# Generated by Django 4.2.14 on 2024-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0004_landing_banner_delete_landingbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_buggy_cloud',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
