# Generated by Django 4.2.14 on 2024-07-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0005_alter_why_buggy_cloud_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_blog',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
