# Generated by Django 4.2.14 on 2024-07-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0006_alter_front_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_list',
            name='subtitle',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
