# Generated by Django 4.2.14 on 2024-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0008_remove_service_list_subtitle_front_blog_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='icons',
            field=models.ImageField(upload_to='static/forntpage/img/banner_icons'),
        ),
        migrations.AlterField(
            model_name='front_blog',
            name='image',
            field=models.ImageField(upload_to='static/forntpage/img/whybuggy'),
        ),
        migrations.AlterField(
            model_name='landing_banner',
            name='image',
            field=models.ImageField(upload_to='static/forntpage/img/landing_banner'),
        ),
        migrations.AlterField(
            model_name='service_list',
            name='image',
            field=models.ImageField(upload_to='static/forntpage/img/servicelist'),
        ),
        migrations.AlterField(
            model_name='why_buggy_cloud',
            name='image',
            field=models.ImageField(upload_to='static/forntpage/img/whybuggy'),
        ),
    ]
