# Generated by Django 4.2.14 on 2024-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
    ]
