# Generated by Django 4.2.14 on 2024-07-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
